# Generated by Django 4.0.2 on 2022-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='ProjectCoverphoto',
            field=models.ImageField(default='defaultcover.jpg', upload_to='images/coverphoto/ProjectDetails/'),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='Projectpicture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='images/Photo/ProjectDetails/'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='ProjectDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='ProjectName',
            field=models.CharField(max_length=100, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='ProjectPOCname',
            field=models.CharField(max_length=100, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='ProjectPOCnum',
            field=models.CharField(max_length=10, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='ProjectTechnicalspecification',
            field=models.FileField(upload_to='doc/', verbose_name='Technical specification'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='ProjectWhitepapers',
            field=models.FileField(blank=True, upload_to='doc/whitepapers', verbose_name='White papers'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='Projectdate',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='Projectlink',
            field=models.URLField(help_text='url link'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='Projectype',
            field=models.TextField(choices=[('Online', 'Online'), ('Physical', 'Physical')], verbose_name='Type'),
        ),
    ]
