# Generated by Django 4.0.2 on 2022-03-28 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_projectdetails_projectcoverphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorymember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatType', models.CharField(max_length=20, verbose_name='Membership type')),
            ],
        ),
        migrations.CreateModel(
            name='TenureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.DateField(verbose_name='Current Active year')),
            ],
        ),
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Membername')),
                ('pic', models.ImageField(default='default.jpg', help_text='The size must be --- and the resoultion is ---', upload_to='images/membersphotos/', verbose_name='Member photo')),
                ('CategoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.categorymember')),
                ('MembershipYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tenuredetails')),
            ],
        ),
    ]
