# Generated by Django 4.0.2 on 2022-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_categorymember_tenuredetails_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenuredetails',
            name='Year',
            field=models.CharField(max_length=8, verbose_name='for eg: 2021-22'),
        ),
    ]
