# Generated by Django 4.0.2 on 2022-03-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_tenuredetails_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='socialsite1',
            field=models.URLField(blank=True, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='membership',
            name='socialsite2',
            field=models.URLField(blank=True, verbose_name='Linkedin link'),
        ),
        migrations.AddField(
            model_name='membership',
            name='socialsite3',
            field=models.URLField(blank=True, verbose_name='Instagram link'),
        ),
    ]
