# Generated by Django 4.0.2 on 2022-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_eventdetails_eventdetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetail',
            old_name='Projectpicture',
            new_name='ProjectIcon',
        ),
        migrations.RemoveField(
            model_name='programdetail',
            name='Description',
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='EventIcon',
            field=models.ImageField(default='default.jpg', upload_to='images/Photo/Event/'),
        ),
        migrations.AddField(
            model_name='programdetail',
            name='ProgramIcon',
            field=models.ImageField(default='default.jpg', upload_to='images/Photo/Program/'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='serviceIcon',
            field=models.ImageField(default='default.jpg', upload_to='images/Photo/services/'),
        ),
    ]
