# Generated by Django 4.0.2 on 2022-03-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_projectpicture_projectdetail_projecticon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenuredetail',
            name='Year',
            field=models.CharField(help_text='for eg: 2021-22', max_length=8, verbose_name='year'),
        ),
    ]
